#ifndef HEADER_ERROR
#define HEADER_ERROR

typedef enum _ERROR
{
    ERROR_NONE,
    ERROR_UNEXPECTED,
    ERROR_SHUTDOWN,
    ERROR_CARD_READING_FAIL,
    ERROR_PIN_VERIFICATION_FAIL,
    ERROR_GET_BALANCE_ERROR,
    ERROR_GET_DEPOSIT_ERROR,
    ERROR_GET_WITHDRAW_ERROR,
    ERROR_END
}ERROR;

void set_error(ERROR e);
ERROR get_error();

#endif //HEADER_ERROR