#ifndef HEADER_STATUS
#define HEADER_STATUS

typedef enum _STATUS
{
    STATUS_IDLE,
    STATUS_CARD_DETECTING,
    STATUS_CARD_READING,
    STATUS_CARD_READING_ERROR,
    STATUS_CARD_READING_DONE,
    STATUS_PIN_INPUT,
    STATUS_PIN_CHECKING,
    STATUS_PIN_CHECKING_ERROR,
    STATUS_PIN_CHECKING_SUCCESS,
    STATUS_DISPLAY_BALANCE,
    STATUS_DISPLAY_DEPOSIT,
    STATUS_DISPLAY_WITHDRAW,
    STATUS_FINISH_ACTION,
    STATUS_FINISH_ACTION_CARD_REMOVE,
    STATUS_END
}STATUS;

void set_status(STATUS s);
STATUS get_status();

#endif //HEADER_STATUS